### ISSUE TITLE
Recieving java.lang.IllegalArgumentException: target cannot be null

### ISSUE THREAD

**Issue by EliasMPJunior** [vidageek/mirror#65]
Hello,

This project sounds awesome! But I've tried to start using it and wasn't able to.

The code bellow is what I have done:

Class<?> classSpec = new Mirror().reflectClass(classPath); // classPath - My own class

new Mirror().on(classSpec).invoke().setterFor(objectColumnName).withValue(columnValue); 

// objectColumnName and columnValue are String and are OK.

I also tried the the string classPath instead of Class classSpec, but got the same result.

Trace is here:

java.lang.IllegalArgumentException: target cannot be null
    at net.vidageek.mirror.DefaultAccessorsController.<init>(DefaultAccessorsController.java:28)
    at net.vidageek.mirror.dsl.Mirror.on(Mirror.java:92)
    at net.vidageek.mirror.invoke.DefaultSetterMethodHandler.withValue(DefaultSetterMethodHandler.java:21)
    at minerva.block.zeus.command.Zeus_PersistDynamicObjectCommand.execute(Zeus_PersistDynamicObjectCommand.java:91)
    at minerva.gaia.control.EngineControl.start(EngineControl.java:95)
    at minerva.maia.control.EngineControl.start(EngineControl.java:178)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Best regards,

Elias

**Comment by jonasabreu** [comment]
Hello Elias,

Can you add the stacktrace you're getting? From what I see some value
passed is null (Mirror checks all the values passed) but I cannot see which
one.

Best regards,

Jonas Abreu

VidaGeek.net - http://vidageek.net
AdaptIdeas - http://www.adaptideas.com.br
